sonar.projectKey=ifs24028-pabwe2026-nextjs
sonar.projectName=ifs24028-pabwe2026-nextjs

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**,.next/**,next.config.*,**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx